### ISSUE TITLE
Migrate from Full Framework to .NET Core 2.0 & .NET Standard 2.0

### ISSUE THREAD

**Issue by jolmari** [jolmari/netcore-wcf-service-proxy#8]
ASP.NET Core application project relies on the full 4.6 framework. Figure out a way to drop reliance on System.ServiceModel and migrate to use only the .NET Core 2 framework.

**Comment by epozsh** [comment]
Is this project working?Cause following ur steps on Readme i missing System.ServiceModel

**Comment by jolmari** [comment]
I tried running the solution with a fresh clone and it works locally. Can you post some error information? Does NuGet fail to load the System.Private.ServiceModel dependency, or is this a runtime error?

**Comment by epozsh** [comment]
Yes i think nuget problem, this is printscreen
![screen](https://user-images.githubusercontent.com/23194476/30177566-f0c96c3e-940e-11e7-8963-fbfcc002dc34.png)

**Comment by epozsh** [comment]
@jolmari  ok this error dissapeared after installing the  .net core 2 runtime i think, or Microsoft .NET Framework 4.6 Targeting Pack.

**Comment by jolmari** [comment]
Ok, good that the problem was resolved!

**Comment by epozsh** [comment]
@jolmari  Hello again, i am getting this error
do you know why?
Same happens when i run tests
![image](https://user-images.githubusercontent.com/23194476/31881463-3f10bcc0-b7ec-11e7-8388-f3007f3048ac.png)

![image](https://user-images.githubusercontent.com/23194476/31881518-6e676492-b7ec-11e7-8425-8b94b363aa9a.png)

**Comment by jolmari** [comment]
To me this looks like the WCF Service was not started correctly, can you try connecting manually to the service ex. with Chrome and see if the CountryService is responding?

**Comment by epozsh** [comment]
On http://localhost:8080/CountryService.svc
i get this, is this have to do with my pc?
![wcf](https://user-images.githubusercontent.com/23194476/31886291-651cc5c0-b7fc-11e7-8ccf-7d062e6668da.png)

Edit

i free some memory and now i get this 
![wcf1](https://user-images.githubusercontent.com/23194476/31886466-0b23a966-b7fd-11e7-87f7-af88864a19a7.png)
But still get same error

**Comment by epozsh** [comment]
Ok sorry for inconvience, the error gone, i had insufficient memory after freed 10% of total memory it worked

**Comment by jolmari** [comment]
Yeah, was about to answer that WCF Services start incorrectly if your PC's memory is low. Glad to hear you figured it out!
